// Validates the JavaScript port against reference trajectories generated by the
// original PyTorch MotorNet (see test/refs.json, test/gru_ref.json). The Python
// reference runs in float32; this port runs in float64, so small numerical
// divergence is expected — especially after many steps of the chaotic arm
// dynamics. We report the maximum absolute deviation for each configuration.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import {
  RigidTendonArm26, CompliantTendonArm26, ReluPointMass24, Reacher, Effector,
} from '../src/effector.js';
import { TwoDofArm } from '../src/skeleton.js';
import {
  RigidTendonHillMuscle, RigidTendonHillMuscleThelen, MujocoHillMuscle, ReluMuscle,
} from '../src/muscle.js';
import { PolicyGRU } from '../src/policy.js';

const here = dirname(fileURLToPath(import.meta.url));
const refs = JSON.parse(readFileSync(join(here, 'refs.json'), 'utf8'));

const rep = (a) => (Array.isArray(a) ? a : [a]);

// Max abs diff between a reference (with leading batch dim) and a JS state.
function diffState(ref, js) {
  // ref: [1, ...]; drop batch dim
  const r = ref[0];
  let max = 0;
  const walk = (a, b) => {
    if (Array.isArray(a)) { a.forEach((x, i) => walk(x, b[i])); return; }
    max = Math.max(max, Math.abs(a - b));
  };
  walk(r, js);
  return max;
}

function snapshot(eff) {
  return {
    joint: eff.states.joint,
    cartesian: eff.states.cartesian,
    geometry: eff.states.geometry,
    muscle: eff.states.muscle,
  };
}

function compareSnap(refSnap, eff) {
  const s = snapshot(eff);
  return Math.max(
    diffState(refSnap.joint, s.joint),
    diffState(refSnap.cartesian, s.cartesian),
    diffState(refSnap.geometry, s.geometry),
    diffState(refSnap.muscle, s.muscle),
  );
}

function runCase(name, makeEff, jointState, actions) {
  const ref = refs[name];
  const eff = makeEff();
  eff.reset({ jointState });
  let maxDiff = compareSnap(ref.init, eff);
  let firstStepDiff = 0;
  for (let t = 0; t < actions.length; t++) {
    eff.step(actions[t]);
    const d = compareSnap(ref.steps[t], eff);
    if (t === 0) firstStepDiff = d;
    maxDiff = Math.max(maxDiff, d);
  }
  return { maxDiff, firstStepDiff };
}

const acts6 = [
  ...Array(5).fill([0.3, 0.0, 0.6, 0.0, 0.2, 0.1]),
  ...Array(5).fill([0.0, 0.5, 0.0, 0.4, 0.1, 0.3]),
];
const acts4 = [
  ...Array(5).fill([0.5, 0.0, 0.0, 0.2]),
  ...Array(5).fill([0.0, 0.3, 0.4, 0.0]),
];
const acts3 = [
  ...Array(6).fill([0.4, 0.2, 0.5]),
  ...Array(4).fill([0.1, 0.6, 0.0]),
];

function buildCustomArm() {
  const eff = new Effector({ skeleton: new TwoDofArm(), muscle: new RigidTendonHillMuscleThelen() });
  eff.addMuscle({ pathFixationBody: [0, 1], pathCoordinates: [[-0.15, 0.03], [0.094, 0.017]], name: 'pec', max_isometric_force: 838, tendon_length: 0.039, optimal_muscle_length: 0.134, normalized_slack_muscle_length: 1.48 });
  eff.addMuscle({ pathFixationBody: [0, 0, 1], pathCoordinates: [[0.14, 0.0], [0.05, -0.0], [0.153, 0.0]], name: 'delt', max_isometric_force: 1207, tendon_length: 0.066, optimal_muscle_length: 0.140, normalized_slack_muscle_length: 1.52 });
  eff.addMuscle({ pathFixationBody: [1, 2], pathCoordinates: [[0.23, 0.001], [0.231, 0.01]], name: 'brad', max_isometric_force: 1422, tendon_length: 0.172, optimal_muscle_length: 0.092, normalized_slack_muscle_length: 1.4 });
  return eff;
}

const cases = [
  ['arm26_rigidhill', () => new RigidTendonArm26({ muscle: new RigidTendonHillMuscle() }), [0.5, 1.0], acts6],
  ['arm26_thelen', () => new RigidTendonArm26({ muscle: new RigidTendonHillMuscleThelen() }), [0.6, 0.9], acts6],
  ['arm26_mujoco', () => new RigidTendonArm26({ muscle: new MujocoHillMuscle() }), [0.6, 0.9], acts6],
  ['arm26_compliant', () => new CompliantTendonArm26(), [0.5, 1.0], acts6],
  ['relupm24', () => new ReluPointMass24(), [0.1, -0.2], acts4],
  ['reacher_relu', () => new Reacher({ muscle: new ReluMuscle() }), [0.5, 1.0], acts4],
  ['custom_arm_thelen', buildCustomArm, [0.6, 0.9], acts3],
];

let pass = true;
console.log('Effector validation (max abs deviation vs PyTorch float32 reference):');
console.log('─'.repeat(72));
for (const [name, makeEff, js, actions] of cases) {
  const { maxDiff, firstStepDiff } = runCase(name, makeEff, js, actions);
  // First-step deviation should be at float32 precision; later steps may drift
  // for chaotic configs, so the overall bar is looser.
  const ok = firstStepDiff < 5e-4 && maxDiff < 5e-2;
  pass = pass && ok;
  console.log(`${ok ? '✓' : '✗'} ${name.padEnd(20)} first-step=${firstStepDiff.toExponential(2)}  max=${maxDiff.toExponential(2)}`);
}

// GRU policy validation
console.log('\nGRU policy validation:');
console.log('─'.repeat(72));
const gruWeights = JSON.parse(readFileSync(join(here, 'gru_weights.json'), 'utf8'));
const gruRef = JSON.parse(readFileSync(join(here, 'gru_ref.json'), 'utf8'));
const pol = new PolicyGRU(gruRef.inp, gruRef.hid, gruRef.out).loadWeights(gruWeights);
let h = pol.initHidden();
let gruMax = 0;
for (const stepRef of gruRef.steps) {
  const { u, h: nh } = pol.forward(stepRef.x, h);
  h = nh;
  const refU = stepRef.u[0];
  const refH = stepRef.h[0][0];
  u.forEach((v, i) => { gruMax = Math.max(gruMax, Math.abs(v - refU[i])); });
  h.forEach((v, i) => { gruMax = Math.max(gruMax, Math.abs(v - refH[i])); });
}
const gruOk = gruMax < 1e-5;
pass = pass && gruOk;
console.log(`${gruOk ? '✓' : '✗'} PolicyGRU forward    max=${gruMax.toExponential(2)}`);

console.log('\n' + (pass ? 'ALL CHECKS PASSED' : 'SOME CHECKS FAILED'));
process.exit(pass ? 0 : 1);
